# Generated by Django 5.0.3 on 2024-04-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_offer_id_alter_offer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offer',
            table='Offers',
        ),
    ]
