# Generated by Django 5.0.3 on 2024-04-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('img_link', models.TextField()),
                ('condition', models.CharField(blank=True, max_length=2, null=True)),
                ('stickerstring', models.TextField(blank=True, null=True)),
                ('inspect', models.TextField()),
                ('rarity', models.TextField()),
                ('category', models.TextField()),
                ('listed', models.BooleanField(default=False)),
                ('tradeable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
