# Generated by Django 5.0.3 on 2024-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
