# Generated by Django 5.0.3 on 2024-04-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
