# Generated by Django 5.0.3 on 2024-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_rename_item_id_offer_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inspect',
            field=models.TextField(unique=True),
        ),
    ]
