# Generated by Django 5.0.3 on 2024-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_offer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='sale_date',
        ),
    ]
