# Generated by Django 5.0.3 on 2024-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_remove_offer_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
