# Generated by Django 5.0.3 on 2024-04-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0004_alter_offer_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('value', models.IntegerField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='offers.offer')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
