# Generated by Django 5.0.3 on 2024-04-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='transactions.transaction')),
            ],
            options={
                'db_table': 'Ratings',
            },
        ),
    ]
