# Generated by Django 5.0.3 on 2024-05-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_offer_owner'),
        ('transactions', '0006_alter_transaction_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_transaction', to='offers.offer'),
        ),
    ]
