# Generated by Django 5.0.3 on 2024-05-15 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_closed_date_alter_transaction_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
