# Generated by Django 5.0.3 on 2024-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_steam_tradelink_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='Wallets',
        ),
    ]
