# Generated by Django 5.0.3 on 2024-04-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_table_alter_wallet_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user_id',
        ),
    ]
