# Generated by Django 5.0.3 on 2024-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
